### ISSUE TITLE
Bandwidth inputs into KernSur function? 

### ISSUE THREAD

**Issue by jpspeng** [larmarange/prevR#17]
Hi - was looking at the code for the kde function, and I'm wondering why the bandwidths are divided by 2 here? 

https://github.com/larmarange/prevR/blob/aec45026be27bc185c8ea7da13f449a6cb76a12d/R/kde.prevR.r#L251

Thanks in advance!

**Comment by larmarange** [comment]
This choice is explained in https://journals.openedition.org/cybergeo/24606  paragraph 42.

A Gaussian kernel is infinite but very concentrated around the centre. If you choose a bandwidth equal to `r / 2`, then 86% of the kernel’s intensity will ly within a circle of radius `r` around the centre.

**Comment by larmarange** [comment]
In prevR,  the value of `r` is calculated to correspond to radii of the same number of observations.  A visual summary could be found in Figure 1 of this paper in *AIDS* journal: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4247267/

**Comment by jpspeng** [comment]
Got it, thanks so much for responding @larmarange. Appreciate it.
