### ISSUE TITLE
Warnings from rlang and ggplot

### ISSUE THREAD

**Issue by monitoringhsd** [larmarange/prevR#24]
Hello there,

I have tried to run example scripts from [https://cran.r-project.org/web/packages/prevR/vignettes/intro_prevR.html](url) and got the following after running `quick.prevR(fdhs)`:

Warning messages:
1: Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.
Please use `as_label()` or `as_name()` instead.
This warning is displayed once per session. 
2: The dot-dot notation (`..level..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(level)` instead.
ℹ The deprecated feature was likely used in the prevR package.
  Please report the issue at <https://github.com/larmarange/prevR/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
3: The following aesthetics were dropped during statistical transformation: fill
ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor? 
4: The following aesthetics were dropped during statistical transformation: fill
ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor? 

I am posting here just to let you know about those.

**Comment by larmarange** [comment]
Thank you for your feedback. I will try to update the package as soon as I find some time

**Comment by larmarange** [comment]
Should be fixed in the dev version
