### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [larmarange/prevR#27]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`prevR` imports 'rgdal', 'maptools' using `rgdal::writeOGR` as found by `pkgapi`, in NAMESPACE (as are `maptools functions not in code), `rgdal::writeOGR` in R/export.prevR.r. `sf::st_write`, `terra::writeVector` can replace `rgdal::writeOGR`. Please fix best by June, latest October 2023.

**Comment by larmarange** [comment]
Thank you for your feedback

I will prepare a fix and a new release in May

**Comment by larmarange** [comment]
Thanks a lot

A new version is now on cran
